### ISSUE TITLE
failed to update weather: Attempt to decode JSON with unexpected mimetype

### ISSUE THREAD

**Issue by agners** [siku2/hass-srf-weather#7]
It seems that something broke this integration

```
2022-04-08 09:23:39 ERROR (MainThread) [custom_components.srf_weather.weather] failed to update weather
Traceback (most recent call last):
  File "/workspaces/core/config/custom_components/srf_weather/weather.py", line 297, in async_update
    await self.__update()
  File "/workspaces/core/config/custom_components/srf_weather/weather.py", line 211, in __update
    data = await _get(self.hass, self._api_data, url)
  File "/workspaces/core/config/custom_components/srf_weather/weather.py", line 119, in _get
    data = await resp.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.srgssr.ch/srf-meteo/forecast/x,y')
```

**Comment by agners** [comment]
Fixed by #8.

**Comment by agners** [comment]
FWIW, also added the logos to the brands repo: https://github.com/home-assistant/brands/pull/3329

@siku2 what do you think, with this fixed is it maybe time for a new release?

**Comment by siku2** [comment]
Thanks for reminding me. I was gonna create a new release after merging your PR but then completely forgot about it.

**Comment by siku2** [comment]
Life got in the way, but I finally managed to release a new version!
